name: example_lint
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  analyzer: ^4.0.0
  custom_lint_builder:
    git: 
      url: git@github.com:TimWhiting/dart_custom_lint
      path: packages/custom_lint_builder
      ref: git_dependency_fix

dependency_overrides:
  custom_lint:
    path: ../../